### PR TITLE
Fix setting postProcessor args

### PR DESCRIPTION
**Pull request by miapuffia**
Added in missing postprocessor-args function

### CODE REVIEW

**Comment by norkunas** [comment]
Thank you. Could you improve the commit message? Something like to `Fix setting postProcessor args` ? :slightly_smiling_face:

**Comment by miapuffia** [comment]
I think I did it haha

**Comment by norkunas** [comment]
> I think I did it haha

with adding 3rd commit, not renaming existing one :slightly_smiling_face:

**Comment by norkunas** [comment]
Thank you @miapuffia

**Pull request merged**
