### PR TITLE
Added getInfo method and upgraded phpunit

### PR DESCRIPTION
**Pull request by greghunt**
I needed to grab the video meta before doing a full download so I added this method. 

I also upgraded phpunit in the process since I was getting some warnings with my test.

### CODE REVIEW

**Comment by norkunas** [comment]
Hey.
This is also achievable with `skip-download = true`, did you try it? :)

**Comment by greghunt** [comment]
No, didn't see that! I'll give it a shot as well, thanks

**Comment by norkunas** [comment]
One difference from your added method is that `download` writes metadata to filesystem. If you want to avoid this I can consider merging this :)

**Comment by greghunt** [comment]
That would be nice!

**Comment by norkunas** [comment]
Could you fix style issues? I'd merge after :)

**Comment by norkunas** [comment]
Thank you @greghunt

**Pull request merged**
