### PR TITLE
Return exception for geoblocked videos

### PR DESCRIPTION
**Pull request by sheriffmarley**
There are cases when videos are geoblocked by youtube. Then this error is returned by youtube-dl "The uploader has not made this video available in your country."

### CODE REVIEW

**Comment by norkunas** [comment]
Hello, thanks for your contribution. Could you get rid of the merge commit because it's already in master and squash everything to a single commit?

**Comment by sheriffmarley** [comment]
Sorry, but how do I do that?

**Comment by sheriffmarley** [comment]
Sorry, but i don't have a clue what you're asking me to do

**Comment by norkunas** [comment]
If you don't know how to do that then you could make a new clean pull requests only with your changes.
Also you should fix code style https://github.styleci.io/analyses/8QnyG3

**Pull request closed without merging**
