### PR TITLE
Check final file and set proper filename

### LINKED ISSUE #4: Bad \SplFileInfo instance when extracting audio
```
$yt = new \YoutubeDl\YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0,
    'output' => '%(id)s.%(ext)s',
]);

$a = $yt->download('https://www.youtube.com/watch?v=IwYm1m1rKd8');
$basename = $a->getBasename(); // IwYm1m1rKd8.webm while it should be IwYm1m1rKd8.mp3
```

### PR DESCRIPTION
**Pull request by dopesong**
Fix #4 

By fixing this, I also found and resolved another problem:

```php
<?php

require_once "vendor/autoload.php";

$yt = new \YoutubeDl\YoutubeDl([
    'output' => '%(id)s.%(ext)s',
]);

$a = $yt->download('https://www.youtube.com/watch?v=IwYm1m1rKd8');
$basename = $a->getFile()->getBasename();

echo $basename;
```
Returned: `IwYm1m1rKd8.mp4`

File found in dir: `IwYm1m1rKd8.mkv`

### CODE REVIEW

**Comment by norkunas** [comment]
@dopesong could you change this PR to comply with symfony standards? :) as I prefer them.

**Comment by dopesong** [comment]
@norkunas Could you comment places which you want to change? Because I see that your old code also with spaces around dots. (Line 149, 152, etc...)

**Comment by norkunas** [comment]
@dopesong code at 177-178 lines should be in single line also same for 189-190 lines. Also configuration options should be unaligned. Thanks.

**Comment by dopesong** [comment]
Interesting thing about StyleCi.

Symfony standards says: Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator;

**Comment by norkunas** [comment]
Yes, this is the thing which I don't like about symfony cs :( I think this reduce readability when there is no spaces around concatenation.

**Comment by dopesong** [comment]
I also prefer to use aligned key value pairs and wrap long methods because to work with long lines on notebook really sucks. 

So I think we should stay on full symfony standards or use best practices for us. What do you think?

**Comment by norkunas** [comment]
@dopesong ok, I agree with you.

**Comment by norkunas** [comment]
Can you rebase now?

**Comment by dopesong** [comment]
Sure, one moment

**Comment by dopesong** [comment]
Should be ok now :+1:

**Comment by norkunas** [comment]
Thank you @dopesong

**Comment by dopesong** [comment]
We need to add missing php docs. I will add them latter ;)

**Comment by norkunas** [comment]
:+1:

**Pull request merged**
