### PR TITLE
set youtube-dl default binPath

### PR DESCRIPTION
**Pull request by IndraGunawan**

### CODE REVIEW

**Comment by norkunas** [comment]
Thanks for the PR, but I think it would be better to update lib to use ```Symfony\Component\Process\ExecutableFinder``` and let it automatically find the binary

**Comment by norkunas** [comment]
I don't like that getter acts as a setter

**Comment by IndraGunawan** [comment]
i use that just as final option. if user use the setBinPath, so we dont need find the executeable.
another option is how if i add 2nd argument to constructor, so if user does not set the binPath then find the youtube-dl binary?

**Comment by norkunas** [comment]
I think would be nice to add method named ```resolveBinary``` or smth, which would check if binPath was set then return it and if not then use the executable finder and if executable not found then throw an exception

**Comment by IndraGunawan** [comment]
when the resolveBinary method called?

**Comment by norkunas** [comment]
@IndraGunawan please check 661f1c3

**Comment by IndraGunawan** [comment]
thanks @norkunas for your code :D

**Pull request closed without merging**
