### PR TITLE
Add Flac extension to allowedAudioFormats

### PR DESCRIPTION
**Pull request by kardoqadir**
Add Flac extension to allowedAudioFormats variable

### CODE REVIEW

**Comment by norkunas** [comment]
Thank you, but please fix style ci issue.

**Comment by kardoqadir** [comment]
Thanks, I just add the Flac to the list and regarding the issue can u help me to fix it? Details about style ci issue is not working..

**Comment by norkunas** [comment]
image

**Comment by norkunas** [comment]
The space is missing after 'wav',

**Comment by norkunas** [comment]
Thank you.

**Pull request merged**
